name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the file
        run: |
          cd src
          cp stacked-cards.js ../dist/stacked-cards.js

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/stacked-cards.js
